// ALL_ANSWER_INDEX 所有答过题的索引
export const ALL_ANSWER_INDEX = 'ALL_ANSWER_INDEX';


// ALL_ERROR_INDEX 所有错题索引
export const ALL_ERROR_INDEX = 'ALL_ERROR_INDEX';

// ALL_ERROR_SUCCESS_INDEX 所有错题，又回答正确索引
export const ALL_ERROR_SUCCESS_INDEX = 'ALL_ERROR_SUCCESS_INDEX';